sudo: required
services:
- docker
script:
- bash scripts/docker_auth && travis_wait 40 docker build -t deiwin/take-care .
deploy:
  provider: script
  script: bash scripts/docker_push
  on:
    branch: master
env:
  global:
  - secure: cFYpmOYzlfjTugGiEFblTWhh39CeqxBWChiQ/RO6zSWJoF0hj+MNlYwjyoTlcdf8K2s9k70uFDywp3jmwcEWXTYSCA9arVa3Zb3HUETUnRB0ABN7Kd4nGDoC06Ng/ccsH4JPKqWS8zWL1mG5R9iBGHjmLYP5WRpEdqQ4iFfeSmIMb8GTfDhB5s6221lT3t63CdD9hPg9earT4vDztmz/GZ9Yvg+wUaWy91vOb2EXd13YGWuo5C+rk5DXOQ+hiVlyFqUwl6V0RHr/wuzgHPYGJho0TNMa/mSbKoidYtJubcDOQw2+Uv9ubXYhiPZ0fBvEVgmcZi8Q3gHdh1NvntNwddsHh3Yb1+JIFFmqZGih/X3/6CY5sS7SnE4wUXe1Zf+1gkkVQKUcd7lkrslETdP+fLvzAST/zEx9I150ld161/18+1WuLAlw07Dn+Wx0hluMcV8eMr1DkEIzeNwbjABiVEkgUjby3z1voAbwBzqecgYnzCO0lUfhfH7liEaPzyypVq3rksiS41txy5cJXjGp96YoCDl8vnLpp9hxTzpDt40ckIlOFSXMnnfsrg5ZqoT+vPi84YYvTdJ32FIcYtymE3jCJ5vEig9S3t+pBraS41v4n42CIZXGsy0OzMpVbr7lZS5PX9Lco4t/Tlzt7+42aYtkYvP0xj9AtVWPgmBFkT0=
  - secure: JzVISmaxK2A7cqRzejOOc6kolWJERZ+XhwvViaJif2ve3080+4RWuUGLfVVbSvnNQbN6uc/Bhy3jHfF5REqwTUlKcAuuuLwM46B4wvnLaTmZATSFctbOk5RQM83fgdwlPGh156hL1H4M89GmB5vygch4oCjoLccKztuv3lycutPFmlvVbG+m9yOA3p+KEQJUlnNkOTdqgd11ml30EotVjAOn5R1GMd2qf8iJqbf46+mhcIXZ0LQ/PeOyavgu48gwGXRkVv85K0j9/YyS16WrxkObMRuQ65GmtU5iMEVWWGbQN8V3oGLQdKRR9AV/HEaJAc2Vea67gwzfOkXIC+5hMQPc0MaGkJFfw3+LHBdj2eUKpaNlBDVRHfZtn3xIQ1wszYNfaOsGK6gr3dtndPTN5ujIIRC2abyWjGXcWkgAg+9zKzcKnZM/386Gegt1Jo5s6/K2Eckhg74VnHNEwHRkRpnRAkbQVhh2z9Za7ADOZJyFkvx6JkjfXSMYAvMrIJnpyf3r+7TefuvrXqTHo/0gvg8r+SsFo0aJa2dSXug4jDTnI4iUUGR/efqmZ5+OaKBQNSsKrIV0CBbWXDQRpbySJslg5u1KXHtTVcq0GVjtr9O36DbJQTlZtsROsqTeDU3NPx+N9Dcpj5bh6XPwppddfXd8AQZOvg1JFZnve/yJSo8=
