#!/bin/bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
"$DIR/docker_auth"

image="deiwin/take-care"

ver_tag="$image:$(git describe --tags --always --dirty)"
docker tag "$image" "$ver_tag"
docker push "$ver_tag"

latest_tag="$image:latest"
docker tag "$image" "$latest_tag"
docker push "$latest_tag"
